services:
    api: 
      build: .
      depends_on:
        - postgres
      ports:
        - 80:8000
      # env_file:
      #     - .env
      environment:
          - DATABASE_URL=${DATABASE_URL}
          - SECRET_KEY=${SECRET_KEY}
          - ALGORITHM =${ALGORITHM}
          - ACCESS_TOKEN_EXPIRE_MINUTES = ${ACCESS_TOKEN_EXPIRE_MINUTES}
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: